// Proxy seguro Julia v4 - catalogo base + scraping ao vivo
// Chave API: variavel de ambiente ANTHROPIC_API_KEY no Vercel
let catalogCache = null;
let catalogCacheTime = 0;
const CACHE_TTL = 23 * 60 * 60 * 1000;

// Catalogo base coletado 11/06/2026 - usado como fallback garantido
const CATALOGO_BASE = [
  {n:'Conjunto Coracao Turquesa Prata',p:'R$129,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-turquesa-prata/'},
    {n:'Conjunto Gota Dourado',p:'R$129,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-gota-dourado/'},
      {n:'Conjunto Coracao Madre Perola Prata',p:'R$179,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-madre-perola-prata/'},
        {n:'Conjunto Coracao Turmalina Verde Prata',p:'R$109,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-turmalina-verde-prata/'},
          {n:'Conjunto Coracao Lilas Dourado',p:'R$129,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-lilas-dourado/'},
            {n:'Conjunto Coracao Vazado Dourado',p:'R$135,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-vazado-dourado/'},
              {n:'Conjunto Coracao Turmalina Verde Claro Dourado',p:'R$145,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-turmalina-verde-claro-dourado/'},
                {n:'Conjunto Coracao Turquesa Dourado',p:'R$129,90',u:'https://www.usejulianacastilho.com/produtos/conjunto-coracao-turquesa-dourado/'},
                  {n:'Conjunto Nossa Senhora Dourado',p:'R$148,00',u:'https://www.usejulianacastilho.com/produtos/conjunto-nossa-senhora-dourado/'},
                    {n:'Conjunto Nossa Senhora Prata',p:'R$120,00',u:'https://www.usejulianacastilho.com/produtos/conjunto-nossa-senhora-prata/'},
                      {n:'Conjunto Ponto de Luz Dourado',p:'R$108,00',u:'https://www.usejulianacastilho.com/produtos/conjunto-ponto-de-luz-dourado/'},
                        {n:'Brinco Fake Triplo com Zirconias Dourado',p:'R$58,00',u:'https://www.usejulianacastilho.com/produtos/brinco-fake-triplo-com-zirconias-dourado/'},
                          {n:'Brinco Perola e Zirconia Dourado',p:'R$35,00',u:'https://www.usejulianacastilho.com/produtos/brinco-perola-e-zirconia-dourado/'},
                            {n:'Brinco Gota Zirconia Dourado',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/brinco-gota-zirconia-dourado/'},
                              {n:'Brinco Coracao Perola Dourado',p:'R$65,00',u:'https://www.usejulianacastilho.com/produtos/brinco-coracao-perola-dourado/'},
                                {n:'Brinco Flor Mini Zirconias Dourado',p:'R$45,00',u:'https://www.usejulianacastilho.com/produtos/brinco-flor-mini-zirconias-dourado/'},
                                  {n:'Brinco Coracao Cravejado Zirconias Dourado',p:'R$35,00',u:'https://www.usejulianacastilho.com/produtos/brinco-coracao-cravejado-de-zirconias-dourado/'},
                                    {n:'Brinco Ponto de Luz Dourado',p:'R$35,00',u:'https://www.usejulianacastilho.com/produtos/brinco-ponto-de-luz-dourado/'},
                                      {n:'Trio Brinco Argolas Zirconias Dourado',p:'R$128,00',u:'https://www.usejulianacastilho.com/produtos/trio-de-brinco-argolas-zirconias-dourado/'},
                                        {n:'Trio Brinco Argolas e Zirconias Dourado',p:'R$108,00',u:'https://www.usejulianacastilho.com/produtos/trio-de-brinco-com-argolas-e-zirconias-dourado/'},
                                          {n:'Brinco Coracao Trabalhado Dourado',p:'R$38,00',u:'https://www.usejulianacastilho.com/produtos/brinco-coracao-trabalhado-dourado/'},
                                            {n:'Brinco Argola Pingentes Zirconia Dourado',p:'R$35,00',u:'https://www.usejulianacastilho.com/produtos/brinco-argola-com-pingentes-de-zirconia-dourado/'},
                                              {n:'Brinco Zirconias Cravejadas Dourado',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/brinco-com-zirconias-cravejadas-dourado/'},
                                                {n:'Brinco Argola Zirconias Coracao Madreperola',p:'R$98,00',u:'https://www.usejulianacastilho.com/produtos/brinco-argola-zirconias-com-coracao-madreperola/'},
                                                  {n:'Brinco Argola Pingente Zirconia',p:'R$45,00',u:'https://www.usejulianacastilho.com/produtos/brinco-argola-com-pingente-de-zirconia/'},
                                                    {n:'Brinco Argola Click Zirconias Cravejadas Dourado',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/brinco-argola-click-zirconias-cravejadas-dourado/'},
                                                      {n:'Brinco Flor Zirconia Madreperola Dourado',p:'R$75,00',u:'https://www.usejulianacastilho.com/produtos/brinco-flor-zirconia-com-madreperola-dourado/'},
                                                        {n:'Brinco Flor Colorida Dourada',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/brinco-flor-colorida-dourada/'},
                                                          {n:'Brinco Argola Click Zirconias Dourada',p:'R$65,00',u:'https://www.usejulianacastilho.com/produtos/brinco-argola-click-zirconias-dourada/'},
                                                            {n:'Brinco Argola Pingente Estrela Zirconia Dourado',p:'R$45,00',u:'https://www.usejulianacastilho.com/produtos/brinco-argola-com-pingente-estrela-zirconia-dourado/'},
                                                              {n:'Colar Ponto de Luz Coracao Dourado',p:'R$98,00',u:'https://www.usejulianacastilho.com/produtos/colar-ponto-de-luz-coracao-dourado/'},
                                                                {n:'Colar Ponto de Luz Dourado',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/colar-ponto-de-luz-dourado/'},
                                                                  {n:'Colar Nossa Senhora Zirconias Dourado',p:'R$128,00',u:'https://www.usejulianacastilho.com/produtos/colar-nossa-senhora-zirconias-dourado/'},
                                                                    {n:'Colar Espirito Santo Cravejado Dourado',p:'R$158,00',u:'https://www.usejulianacastilho.com/produtos/colar-espirito-santo-cravejado-dourado/'},
                                                                      {n:'Choker Fita Grossa Dourado',p:'R$178,00',u:'https://www.usejulianacastilho.com/produtos/choker-fita-grossa-dourado/'},
                                                                        {n:'Colar Nossa Senhora Coracao Zirconia Mini Dourado',p:'R$108,00',u:'https://www.usejulianacastilho.com/produtos/colar-nossa-senhora-e-coracao-zirconia-mini-dourada/'},
                                                                          {n:'Colar Divino Espirito Santo Cravejado Dourado',p:'R$180,00',u:'https://www.usejulianacastilho.com/produtos/colar-divino-espirito-santo-cravejado-dourado/'},
                                                                            {n:'Colar Divino Espirito Santo Cravejado Prata',p:'R$108,00',u:'https://www.usejulianacastilho.com/produtos/colar-divino-espirito-santo-cravejado-prata/'},
                                                                              {n:'Colar Nossa Senhora Zirconias Prata',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/colar-nossa-senhora-zirconias-prata/'},
                                                                                {n:'Colar Nossa Senhora Coracao Zirconia Mini Prata',p:'R$85,00',u:'https://www.usejulianacastilho.com/produtos/colar-nossa-senhora-e-coracao-zirconia-mini-prata/'},
                                                                                ];

                                                                                async function buildSystemPrompt() {
                                                                                  const now = Date.now();
                                                                                    if (catalogCache && (now - catalogCacheTime) < CACHE_TTL) return catalogCache;

                                                                                      // Tentar scraping ao vivo em paralelo (enriquece o catalogo base)
                                                                                        let produtosVivos = [];
                                                                                          try {
                                                                                              const STORE = 'https://www.usejulianacastilho.com';
                                                                                                  const paginas = ['/brincos/', '/colares/', '/dia-dos-namorados/'];
                                                                                                      const seen = new Set();
                                                                                                          const resultados = await Promise.all(
                                                                                                                paginas.map(pg =>
                                                                                                                        fetch(STORE + pg, { headers: {'User-Agent':'JC-Proxy/4.0'}, signal: AbortSignal.timeout(4000) })
                                                                                                                                  .then(r => r.text())
                                                                                                                                            .then(html => {
                                                                                                                                                        const re = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi;
                                                                                                                                                                    const prods = [];
                                                                                                                                                                                let m;
                                                                                                                                                                                            while ((m = re.exec(html)) !== null) {
                                                                                                                                                                                                          try {
                                                                                                                                                                                                                          const d = JSON.parse(m[1]);
                                                                                                                                                                                                                                          if (d['@type']==='Product' && d.name && d.mainEntityOfPage?.['@id']) {
                                                                                                                                                                                                                                                            const url = d.mainEntityOfPage['@id'].replace('https://usejulianacastilho.com', STORE);
                                                                                                                                                                                                                                                                              const slug = url.replace(STORE,'');
                                                                                                                                                                                                                                                                                                if (!seen.has(slug)) {
                                                                                                                                                                                                                                                                                                                    seen.add(slug);
                                                                                                                                                                                                                                                                                                                                        const pr = d.offers?.price || (Array.isArray(d.offers)?d.offers[0]?.price:0) || 0;
                                                                                                                                                                                                                                                                                                                                                            prods.push({n:d.name, p:'R$'+parseFloat(pr).toFixed(2).replace('.',','), u:url});
                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                            } catch(e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                    return prods;
                                                                                                                                                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                                                                                                                                                        .catch(() => [])
                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (const r of resultados) produtosVivos = produtosVivos.concat(r);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Scraping erro:', e.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Mesclar: vivos primeiro, depois base como complemento
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const seen2 = new Set(produtosVivos.map(p => p.u));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const baseFaltante = CATALOGO_BASE.filter(p => !seen2.has(p.u));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const catalogo = produtosVivos.length >= 5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? [...produtosVivos, ...baseFaltante]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : CATALOGO_BASE;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const lista = catalogo.map(p => `- ${p.n} - ${p.p} - ${p.u}`).join('\n');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const fonte = produtosVivos.length >= 5 ? 'ao vivo + base' : 'base local 11/06/2026';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const prompt = `Voce e Julia, consultora virtual de semijoias da Juliana Castilho Semijoias.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    REGRA ABSOLUTA - NUNCA INVENTE PRODUTOS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Voce tem o CATALOGO OFICIAL abaixo. Estas sao as UNICAS pecas que existem na loja.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    E ESTRITAMENTE PROIBIDO:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Inventar, criar ou mencionar qualquer produto fora desta lista.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Sugerir produtos parecidos que nao estejam na lista.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Criar URLs diferentes das listadas.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Mencionar precos diferentes dos listados.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Se a cliente pedir algo que nao existe: diga honestamente que nao temos esse item e sugira alternativas reais da lista.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Esta regra tem PRIORIDADE ABSOLUTA sobre qualquer outro comportamento.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CATALOGO OFICIAL (${catalogo.length} produtos - fonte: ${fonte}):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ${lista}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    DIFERENCIAIS DA LOJA:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Ate 12x no cartao / 3x sem juros / 10% desconto no Pix
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Frete gratis acima de R$399 / Garantia 1 ano / Hipoalergenicas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - WhatsApp: (49) 99997-8012 / Instagram: @julianacastilhosemijoias

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    COMO RECOMENDAR:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1. Somente produtos desta lista, nome e URL exatos.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2. Formato: **[Nome]** - [preco] - [link]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3. Maximo 3 produtos por resposta.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    4. Explique por que a peca combina com o pedido da cliente.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    5. Se nao houver produto adequado na lista, diga honestamente.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TOM: acolhedora, elegante, feminina. Portugues brasileiro natural. Respostas curtas (maximo 3 paragrafos).`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      catalogCache = prompt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        catalogCacheTime = now;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return prompt;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default async function handler(req, res) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.setHeader('Access-Control-Allow-Origin', '*');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (req.method === 'OPTIONS') return res.status(200).end();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (req.method !== 'POST') return res.status(405).json({ error: 'Metodo nao permitido' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { messages, max_tokens, model } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const systemPrompt = await buildSystemPrompt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const payload = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        model: model || 'claude-haiku-4-5-20251001',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              max_tokens: max_tokens || 600,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    messages,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          system: systemPrompt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const response = await fetch('https://api.anthropic.com/v1/messages', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'x-api-key': process.env.ANTHROPIC_API_KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'anthropic-version': '2023-06-01'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: JSON.stringify(payload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const data = await response.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const replyText = data.content?.[0]?.text || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return res.status(response.status).json({ reply: replyText, ...data });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('Erro proxy:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(500).json({ error: 'Erro interno' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }